### PR TITLE
[JIRA: CDSADAPTERS-1955] Adding integration dependency changes

### PR DESCRIPTION
**Pull request by Shubho2**
JIRA Link: https://jira.tools.sap/browse/CDSADAPTERS-1955

This PR adds support to show integration dependency in ORD document.

### CODE REVIEW

**Comment by RoshniNaveenaS** [comment]
image

The above subset can be removed as it is throwing an error in metadata validator

**Comment by RoshniNaveenaS** [comment]
image

Can you update the eventResource `ordId`

**Comment by RoshniNaveenaS** [comment]
`apiResources` in `integrationDependencies` should be the corresponding apiResource for the service marked with `cds.external`

**Comment by Shubho2** [comment]
> image
> 
> Can you update the eventResource `ordId`

I have made the changes as you suggested. Could you please check?

**Pull request closed without merging**
